steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/wordpress-comment-moderator',
      '.'
    ]
  
  # Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/wordpress-comment-moderator'
    ]

  # Paso 3: Desplegar la imagen a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'wordpress-comment-moderator',
      '--image', 'gcr.io/$PROJECT_ID/wordpress-comment-moderator',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/wordpress-comment-moderator'

options:
  logging: CLOUD_LOGGING_ONLY